# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InCourage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InCourage
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Fabric'
  pod 'Crashlytics'


  target 'InCourageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InCourageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
